# Generated by Django 5.1.3 on 2025-12-28 14:33

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LevelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                            (4, "Level 4"),
                            (5, "Level 5"),
                        ],
                        help_text="Player / mission level (1–5)",
                        unique=True,
                    ),
                ),
                ("min_required_cards", models.PositiveSmallIntegerField()),
                ("max_required_cards", models.PositiveSmallIntegerField()),
                ("min_enemy_level", models.PositiveSmallIntegerField()),
                ("max_enemy_level", models.PositiveSmallIntegerField()),
                ("min_card_level", models.PositiveSmallIntegerField(default=1)),
                ("max_card_level", models.PositiveSmallIntegerField(default=5)),
                (
                    "max_distinct_card_levels",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="How many different card levels can appear in a mission",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission_id",
                    models.CharField(
                        db_index=True,
                        help_text="Public mission identifier, e.g. XP0",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "image",
                    models.ImageField(
                        help_text="Mission icon / GIF",
                        storage=payments.models.OverwriteStorage(),
                        upload_to=payments.models.ImageUploadPath("missions"),
                    ),
                ),
                (
                    "banner",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Resolved banner URL (derived from image)",
                        max_length=256,
                    ),
                ),
                (
                    "progress_mode",
                    models.CharField(
                        choices=[
                            ("TARGETED", "Targeted"),
                            ("ACCUMULATIVE", "Accumulative"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "time_scope",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="PERMANENT",
                        max_length=16,
                    ),
                ),
                (
                    "resolution_mode",
                    models.CharField(
                        choices=[
                            ("THRESHOLD", "Threshold"),
                            ("COMPETITIVE", "Competitive"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "required_level",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "progress_definition",
                    models.JSONField(
                        help_text='\n        Defines how progress is earned.\n        Examples:\n        - { "type": "card", "vehicle_types": ["TANK", "DRONE"] }\n        - { "type": "points", "per_kill": 10 }\n        '
                    ),
                ),
                (
                    "target_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Only used for TARGETED missions",
                        null=True,
                    ),
                ),
                (
                    "rewards",
                    models.JSONField(help_text="Reward definition (fixed or ranked)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RESOLVING", "Resolving"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("hash_code", models.BigIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Validation identifier, e.g. user_id/all_missions",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("validation_code", models.CharField(max_length=128)),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("player_name", models.CharField(max_length=64)),
                ("score", models.IntegerField(default=0)),
                ("baseline_score", models.IntegerField(default=0)),
                ("rank", models.IntegerField(db_index=True)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "period_key",
                    models.CharField(
                        db_index=True,
                        help_text="Example: 2025-12-16, 2025-W51, 2025-12",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_finalized", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["rank"],
                "unique_together": {("user_id", "period", "period_key")},
            },
        ),
        migrations.CreateModel(
            name="LeaderboardPeriodControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_key", models.CharField(db_index=True, max_length=16)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_finalized", models.BooleanField(default=False)),
                ("rewards_distributed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period", "-period_key"],
                "unique_together": {("period", "period_key")},
            },
        ),
        migrations.CreateModel(
            name="LeaderboardPeriodResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_key", models.CharField(max_length=16)),
                ("user_id", models.CharField(max_length=128)),
                ("player_name", models.CharField(max_length=64)),
                ("rank", models.PositiveIntegerField()),
                ("score", models.PositiveIntegerField()),
                ("finalized_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["period", "period_key"],
                        name="payments_le_period_94bb11_idx",
                    ),
                    models.Index(
                        fields=["user_id"], name="payments_le_user_id_22bad0_idx"
                    ),
                ],
                "unique_together": {("period", "period_key", "rank")},
            },
        ),
        migrations.CreateModel(
            name="LeaderboardReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("reward_type", models.CharField(max_length=32)),
                ("reward_payload", models.JSONField()),
            ],
            options={
                "unique_together": {("period", "rank")},
            },
        ),
    ]
