# Generated by Django 5.1.3 on 2025-12-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="baseline_score",
            field=models.IntegerField(default=0),
        ),
    ]
