# Generated by Django 5.1.3 on 2025-12-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="required_level",
        ),
    ]
