# Generated by Django 5.1.3 on 2026-01-02 22:47

import django.db.models.deletion
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_remove_mission_required_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="level",
            field=models.ForeignKey(
                default=payments.models.default_level_config,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.levelconfig",
            ),
        ),
    ]
