# Generated by Django 5.1.3 on 2025-12-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_leaderboardentry_baseline_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=10)),
                ("rank", models.PositiveIntegerField()),
                ("reward_type", models.CharField(max_length=32)),
                ("reward_payload", models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="is_finalized",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="LeaderboardPeriodResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_key", models.CharField(max_length=16)),
                ("user_id", models.CharField(max_length=128)),
                ("player_name", models.CharField(max_length=64)),
                ("rank", models.PositiveIntegerField()),
                ("score", models.PositiveIntegerField()),
                ("finalized_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["period", "period_key"],
                        name="payments_le_period_94bb11_idx",
                    ),
                    models.Index(
                        fields=["user_id"], name="payments_le_user_id_22bad0_idx"
                    ),
                ],
                "unique_together": {("period", "period_key", "rank")},
            },
        ),
    ]
