# Generated by Django 5.1.3 on 2025-12-17 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_leaderboardreward_leaderboardentry_is_finalized_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leaderboardreward",
            unique_together={("period", "rank")},
        ),
    ]
