# Generated by Django 5.1.3 on 2026-01-02 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_mission_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="payments.levelconfig"
            ),
        ),
    ]
