# Generated by Django 5.1.3 on 2025-12-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_leaderboardreward_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardPeriodControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_key", models.CharField(db_index=True, max_length=16)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_finalized", models.BooleanField(default=False)),
                ("rewards_distributed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period", "-period_key"],
                "unique_together": {("period", "period_key")},
            },
        ),
    ]
