# Generated by Django 5.1.3 on 2026-01-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_mission_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=128)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Only used for TARGETED missions",
                        null=True,
                    ),
                ),
                (
                    "rewards",
                    models.JSONField(help_text="Reward definition (fixed or ranked)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RESOLVING", "Resolving"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("hash_code", models.BigIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
