# Generated by Django 5.1.3 on 2026-01-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_evententry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evententry",
            name="target_value",
        ),
    ]
