# Generated by Django 5.1.3 on 2025-12-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_leaderboardperiodcontrol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboardreward",
            name="period",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
