# Generated by Django 5.1.3 on 2025-12-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_leaderboardreward_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission_id",
                    models.CharField(
                        db_index=True,
                        help_text="Public mission identifier, e.g. XP0",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("banner", models.CharField(blank=True, default="", max_length=256)),
                (
                    "expiry_period",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional expiry rule (e.g. daily, weekly, timestamp-based)",
                        max_length=32,
                    ),
                ),
                (
                    "requirements",
                    models.JSONField(help_text="List of requirement objects"),
                ),
                ("rewards", models.JSONField(help_text="List of reward objects")),
                (
                    "hash_code",
                    models.BigIntegerField(
                        db_index=True, help_text="Server-generated hash for validation"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["mission_id"],
            },
        ),
    ]
