# Generated by Django 5.1.3 on 2026-01-04 11:51

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_remove_evententry_target_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evententry",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="evententry",
            name="banner",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Resolved banner URL (derived from image)",
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="evententry",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Event icon / GIF",
                null=True,
                storage=payments.models.OverwriteStorage(),
                upload_to=payments.models.ImageUploadPath("events"),
            ),
        ),
    ]
