# Generated by Django 5.1.3 on 2025-12-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_mission"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                            (4, "Level 4"),
                            (5, "Level 5"),
                        ],
                        help_text="Player / mission level (1–5)",
                        unique=True,
                    ),
                ),
                ("min_required_cards", models.PositiveSmallIntegerField()),
                ("max_required_cards", models.PositiveSmallIntegerField()),
                ("min_enemy_level", models.PositiveSmallIntegerField()),
                ("max_enemy_level", models.PositiveSmallIntegerField()),
                ("min_card_level", models.PositiveSmallIntegerField(default=1)),
                ("max_card_level", models.PositiveSmallIntegerField(default=5)),
                (
                    "max_distinct_card_levels",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="How many different card levels can appear in a mission",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["level"],
            },
        ),
    ]
