# Generated by Django 5.1.3 on 2026-01-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_evententry_options_evententry_banner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelconfig",
            name="value",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="levelconfig",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Level1"),
                    (2, "Level2"),
                    (3, "Level3"),
                    (4, "Level4"),
                    (5, "Level5"),
                ],
                help_text="Player / mission level (1–5)",
                unique=True,
            ),
        ),
    ]
