# Generated by Django 5.1.3 on 2025-12-20 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_levelconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now,
                help_text="Mission icon / GIF",
                upload_to="missions/",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mission",
            name="expiry_period",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="mission",
            name="hash_code",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="requirements",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="mission",
            name="rewards",
            field=models.JSONField(),
        ),
    ]
