# Generated by Django 5.1.3 on 2026-01-06 17:30

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_levelconfig_value_alter_levelconfig_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelconfig",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Event icon / GIF",
                null=True,
                storage=payments.models.OverwriteStorage(),
                upload_to=payments.models.ImageUploadPath("level_data"),
            ),
        ),
        migrations.AddField(
            model_name="levelconfig",
            name="name",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
