# Generated by Django 5.1.3 on 2025-12-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_mission_image_alter_mission_expiry_period_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Validation identifier, e.g. user_id/all_missions",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("validation_code", models.BigIntegerField(db_index=True)),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
    ]
