# Generated by Django 5.1.3 on 2026-01-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_levelconfig_image_levelconfig_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelconfig",
            name="image_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Resolved banner URL (derived from image)",
                max_length=256,
            ),
        ),
    ]
