# Generated by Django 5.1.3 on 2026-01-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_levelconfig_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="levelconfig",
            name="image_url",
        ),
    ]
