# Generated by Django 5.1.3 on 2025-12-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_validationentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationentry",
            name="validation_code",
            field=models.CharField(max_length=128),
        ),
    ]
