# Generated by Django 5.1.3 on 2025-12-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_alter_validationentry_validation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="banner",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Resolved banner URL (derived from image)",
                max_length=256,
            ),
        ),
    ]
