# Generated by Django 5.1.3 on 2026-01-18 09:16

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_remove_levelconfig_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=128)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Event icon / GIF",
                        null=True,
                        storage=payments.models.OverwriteStorage(),
                        upload_to=payments.models.ImageUploadPath("events"),
                    ),
                ),
                (
                    "banner",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Resolved banner URL (derived from image)",
                        max_length=256,
                    ),
                ),
                ("seen", models.BooleanField(default=False)),
                ("hash_code", models.BigIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
