# Generated by Django 5.1.3 on 2026-01-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_notificationentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationentry",
            name="user_id",
            field=models.CharField(default="None", max_length=128),
            preserve_default=False,
        ),
    ]
