# Generated by Django 5.1.3 on 2026-01-18 09:48

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_notificationentry_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationentry",
            name="banner",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="notificationentry",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=payments.models.OverwriteStorage(),
                upload_to=payments.models.ImageUploadPath("events"),
            ),
        ),
    ]
