# Generated by Django 5.1.3 on 2026-01-18 12:36

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_alter_notificationentry_banner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationentry",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=payments.models.OverwriteStorage(),
                upload_to=payments.models.ImageUploadPath("notifications"),
            ),
        ),
    ]
