# Generated by Django 5.1.3 on 2026-01-18 19:51

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0015_alter_notificationentry_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("NEW_RUNNER", "New Runner"),
                        ],
                        default="STANDARD",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("body", models.CharField(max_length=512)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=payments.models.OverwriteStorage(),
                        upload_to=payments.models.ImageUploadPath("news"),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="notificationentry",
            name="banner",
        ),
    ]
