# Generated by Django 5.1.3 on 2026-01-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_newsentry_remove_notificationentry_banner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsentry",
            old_name="title",
            new_name="brief",
        ),
        migrations.RenameField(
            model_name="newsentry",
            old_name="body",
            new_name="content",
        ),
        migrations.AddField(
            model_name="newsentry",
            name="headline",
            field=models.CharField(default="None", max_length=128),
            preserve_default=False,
        ),
    ]
