# Generated by Django 5.1.3 on 2026-01-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0017_rename_title_newsentry_brief_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententry",
            name="payload_structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STANDARD", "Standard"),
                    ("NEW_RUNNER", "New Runner"),
                    ("RANK_COMPETITION", "Rank Competition"),
                ],
                default="STANDARD",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="newsentry",
            name="article_type",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("NEW_RUNNER", "New Runner"),
                    ("RANK_COMPETITION", "Rank Competition"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
    ]
