# Generated by Django 5.1.3 on 2026-01-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_evententry_payload_structure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententry",
            name="brief",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="evententry",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
