# Generated by Django 5.1.3 on 2026-01-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_evententry_brief_evententry_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententry",
            name="headline",
            field=models.CharField(default="None", max_length=128),
            preserve_default=False,
        ),
    ]
