# Generated by Django 5.1.3 on 2026-01-20 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_evententry_headline"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsManifestState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="newsentry",
            name="article_uid",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="newsentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
