# Generated by Django 5.1.3 on 2026-01-20 19:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0022_alter_newsentry_article_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsentry",
            name="article_uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
