# Generated by Django 5.1.3 on 2026-01-21 10:50

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0023_alter_newsentry_article_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententry",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Event icon / GIF",
                null=True,
                storage=payments.models.OverwriteStorage(),
                upload_to="events/banners/",
            ),
        ),
        migrations.AlterField(
            model_name="levelconfig",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Event icon / GIF",
                null=True,
                storage=payments.models.OverwriteStorage(),
                upload_to="objectives/icons/",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="image",
            field=models.ImageField(
                help_text="Mission icon / GIF",
                storage=payments.models.OverwriteStorage(),
                upload_to="missions/banners/",
            ),
        ),
        migrations.AlterField(
            model_name="newsentry",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=payments.models.OverwriteStorage(),
                upload_to="news/banners/",
            ),
        ),
        migrations.AlterField(
            model_name="notificationentry",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=payments.models.OverwriteStorage(),
                upload_to="notifications/icons/",
            ),
        ),
    ]
