# Generated by Django 5.1.3 on 2026-01-21 19:11

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0024_alter_evententry_image_alter_levelconfig_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententry",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Event banner / GIF",
                null=True,
                storage=payments.models.OverwriteStorage(),
                upload_to="events/icons/",
            ),
        ),
    ]
