# Generated by Django 5.1.3 on 2026-01-24 16:06

import payments.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0025_alter_evententry_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataManifestState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=128)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="notificationentry",
            name="article_uid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name="evententry",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Event banner / GIF",
                null=True,
                storage=payments.models.OverwriteStorage(),
                upload_to="events/banners/",
            ),
        ),
        migrations.AlterField(
            model_name="evententry",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Event icon / GIF",
                null=True,
                storage=payments.models.OverwriteStorage(),
                upload_to="events/icons/",
            ),
        ),
    ]
