# Generated by Django 5.1.3 on 2026-01-26 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0026_datamanifeststate_notificationentry_article_uid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunnerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("icon", models.CharField(max_length=128)),
                ("price", models.PositiveIntegerField(default=0)),
                ("description", models.TextField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["created_at", "updated_at"],
            },
        ),
    ]
