# Generated by Django 5.1.3 on 2026-01-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0027_runnerentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runnerentry",
            name="icon",
        ),
    ]
