# Generated by Django 5.1.3 on 2026-01-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0028_remove_runnerentry_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="runnerentry",
            name="configuration",
            field=models.JSONField(default=dict),
        ),
    ]
