# Generated by Django 5.1.3 on 2026-02-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0029_runnerentry_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="runnerentry",
            name="power",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="runnerentry",
            name="speed",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="runnerentry",
            name="stamina",
            field=models.FloatField(default=1.0),
        ),
    ]
