# Generated by Django 5.1.3 on 2026-02-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0030_runnerentry_power_runnerentry_speed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runnerentry",
            name="configuration",
        ),
    ]
