# Generated by Django 5.1.3 on 2026-02-04 16:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0031_remove_runnerentry_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententry",
            name="event_id",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
