# Generated by Django 5.1.3 on 2026-02-04 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0034_alter_evententry_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententry",
            name="event_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
