# Generated by Django 5.1.3 on 2026-02-05 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0035_alter_evententry_event_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageEntry",
            fields=[
                (
                    "package_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MISSION", "mission"),
                            ("FREE", "free"),
                            ("AD", "ad"),
                            ("PURCHASE", "purchase"),
                        ],
                        default="PURCHASE",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=128, unique=True)),
                ("price", models.PositiveIntegerField(default=0)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("description", models.TextField()),
                (
                    "rewards",
                    models.JSONField(help_text="Reward definition (fixed or ranked)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.RenameModel(
            old_name="DataManifestState",
            new_name="DataManifestStateEntry",
        ),
    ]
