# Generated by Django 5.1.3 on 2026-02-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0036_packageentry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageentry",
            name="price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="packageentry",
            name="rewards",
            field=models.JSONField(blank=True, default={}),
        ),
    ]
