# Generated by Django 5.1.3 on 2026-02-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0037_alter_packageentry_price_alter_packageentry_rewards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageentry",
            name="rewards",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
