# Generated by Django 5.1.3 on 2026-02-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0038_alter_packageentry_rewards"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packageentry",
            options={"ordering": ["price", "title"]},
        ),
        migrations.AlterField(
            model_name="packageentry",
            name="rewards",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="packageentry",
            name="type",
            field=models.CharField(
                choices=[
                    ("MISSION", "Mission"),
                    ("FREE", "Free"),
                    ("AD", "Ad"),
                    ("PURCHASE", "Purchase"),
                    ("BUNDLE", "Bundle"),
                ],
                default="PURCHASE",
                max_length=16,
            ),
        ),
    ]
