# Generated by Django 5.1.3 on 2026-02-08 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0039_alter_packageentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelconfig",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="levelconfig",
            name="level_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
