# Generated by Django 5.1.3 on 2026-02-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0040_levelconfig_created_at_levelconfig_level_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="mission_type",
            field=models.CharField(
                choices=[("DEFAULT", "Default"), ("STANDARD", "Standard")],
                default="STANDARD",
                max_length=16,
            ),
        ),
    ]
