# Generated by Django 5.1.3 on 2026-02-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0041_mission_mission_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="hash_code",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
